### ISSUE TITLE
"Pause" is not possible

### ISSUE THREAD

**Issue by zhibirc** [linuxenko/upnp-rndr#1]
I can't paused video on UPnP renderer. Video itself loading correctly and playing. Then I invoke client.pause(); but nothing happens. The output is { InstanceID: 0, TransportState: 'TRANSITIONING' } Please help me to solve how can I paused a stream. Thanks a lot.

**Comment by linuxenko** [comment]
:unicorn: 

I do not tried it for couple of years, but i should say - it works just fine for me. 
There is [project](https://github.com/linuxenko/umediashare) which works on top of `upnp-rndr` and it [works just fine](https://www.youtube.com/watch?v=pzq_IGg_9LQ) (made specially for this task to remind how does it all work)
I think, the problem you stuck with - is a http server, but i'm not sure, try to install [ums](https://github.com/linuxenko/umediashare/releases) and if it works for you i'll try to help you .

**Comment by zhibirc** [comment]
Thank you very much for quick reaction!

I tried to use your great tool and it correctly (seems like) sends audio/video for playing (both to Samsung TV UPnP renderer and gmediarenderer utility (UPNP-AV renderer daemon on Ubuntu/Mint GNU/Linux)).

But there are some differences... Setting ```pause``` using your tool on the first renderer is not possible (even the appropriate button is hidden), but works perfectly with the second one (gmediarenderer).

I tried to set pause on video through ```client.pause();``` in my nodejs command line utility using the second renderer (see above) and **it works**! Attempt which is described in the top message (trying to set pause with ```client.pause();``` on the first renderer is unsuccessfull).

So, I think that formally current issue can be closed. But tell me please if you know what is the trick/problem with the first renderer?

**Comment by linuxenko** [comment]
Aha, i've asked to run `ums` because there is some "[tricks](https://github.com/linuxenko/umediashare/blob/master/app/controllers/player.js#L17)" with it. Possible problem: your device does not respond currently playing time (maybe it does not recognizable by the tool). It sometimes happens with different video/audio formats, i do not remember which video format works everywhere, but it seems like `mp3` should work with any device i've tried. Lets try mp3 .

**Comment by zhibirc** [comment]
Thanks!

Currently all works as expected unless ```getDuration```, also there is a problem with the following file:
http://commondatastorage.googleapis.com/gtv-videos-bucket/big_buck_bunny_1080p.mp4
Trying to play it with your tool or with my fails:
`ERROR [2017-08-03 14:27:12.488539 | gstreamer] qtdemux10: Error: GStreamer encountered a general stream error. (Debug: qtdemux.c(6370): gst_qtdemux_process_adapter (): /GstPlayBin:play/GstURIDecodeBin:uridecodebin1/GstDecodeBin:decodebin1/GstQTDemux:qtdemux10:
no 'moov' atom within the first 10 MB)
ERROR [2017-08-03 14:27:12.489131 | gstreamer] source: Error: Internal data flow error. (Debug: gstbasesrc.c(2948): gst_base_src_loop (): /GstPlayBin:play/GstURIDecodeBin:uridecodebin1/GstSoupHTTPSrc:source:
streaming task paused, reason error (-5))`
